---
- name: Create essential user directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - Development/repos
    - "Minecraft Servers"
    - Pictures/Wallpapers
