---
- name: Create essential user directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "Minecraft Servers"
    # - Pictures/Wallpapers # Created by chezmoi during symlink setup
