---
# Generated GNOME keybindings snapshot (regenerated 2025-09-16T09:58:21-06:00).
# Regenerate with: scripts/export_gnome_keybindings.sh
# This list is applied by the gnome-settings role.
gnome_keybindings:

  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings", value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding", value: "'<Super>s'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command", value: "'flatpak run com.valvesoftware.Steam'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name", value: "'Open Steam'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding", value: "'<Super>d'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command", value: "'flatpak run com.discordapp.Discord'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name", value: "'Open Discord'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding", value: "'<Super>n'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command", value: "'gnome-text-editor'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name", value: "'Open Notes'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/binding", value: "'<Super>w'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/command", value: "'sh /home/hcnureth/scripts/start_work_env.sh &'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/name", value: "'Open Work'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/binding", value: "'<Super>b'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/command", value: "'flatpak run com.google.Chrome --profile-directory=\"Default\"'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/name", value: "'Open Chrome'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/binding", value: "'<Super>g'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/command", value: "'flatpak run com.google.Chrome https://gemini.google.com/ --profile-directory=\"Default\"'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/name", value: "'Open Gemini'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/binding", value: "'<Super>y'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/command", value: "'flatpak run com.google.Chrome https://youtube.com/ --profile-directory=\"Default\"'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/name", value: "'Open YouTube'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/binding", value: "'<Super>p'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/command", value: "'flatpak run com.google.Chrome https://messages.google.com/ --profile-directory=\"Default\"'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/name", value: "'Open Phone'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/binding", value: "'<Super>bracketright'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/command", value: "'simplescreenrecorder'" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/name", value: "'Record Screen'" }
  - { key: "/org/gnome/desktop/wm/keybindings/close", value: "['<Super>x']" }
  - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left", value: "['<Super><Shift>Page_Up', '<Super><Shift><Alt>Left', '<Control><Shift><Alt>Left']" }
  - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right", value: "['<Super><Shift>Page_Down', '<Super><Shift><Alt>Right', '<Control><Shift><Alt>Right']" }
  - { key: "/org/gnome/desktop/wm/keybindings/panel-main-menu", value: "['<Alt>F1']" }
  - { key: "/org/gnome/desktop/wm/keybindings/switch-applications", value: "['<Alt>Tab']" }
  - { key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward", value: "['<Shift><Alt>Tab']" }
  - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1", value: "['<Super>1']" }
  - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2", value: "['<Super>2']" }
  - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3", value: "['<Super>3']" }
  - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4", value: "['<Super>4']" }
  - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left", value: "['<Super>Page_Up', '<Super><Alt>Left', '<Control><Alt>Left']" }
  - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right", value: "['<Super>Page_Down', '<Super><Alt>Right', '<Control><Alt>Right']" }
  - { key: "/org/gnome/desktop/wm/keybindings/toggle-fullscreen", value: "['<Shift><Super>f']" }
  - { key: "/org/gnome/desktop/wm/keybindings/unmaximize", value: "['<Super>Down', '<Alt>F5']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/battery-status", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/battery-status-static", value: "['XF86Battery']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/calculator", value: "['<Super>bracketleft']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/calculator-static", value: "['XF86Calculator']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/control-center", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/control-center-static", value: "['XF86Tools']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings", value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/decrease-text-size", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/eject", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/eject-static", value: "['XF86Eject']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/email-static", value: "['XF86Mail']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/hibernate", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/hibernate-static", value: "['XF86Suspend', 'XF86Hibernate']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/home", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/home-static", value: "['XF86Explorer']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/increase-text-size", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-down", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-down-static", value: "['XF86KbdBrightnessDown']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-toggle", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-toggle-static", value: "['XF86KbdLightOnOff']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-up", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-up-static", value: "['XF86KbdBrightnessUp']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/media", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/media-static", value: "['XF86AudioMedia']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/mic-mute", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/mic-mute-static", value: "['XF86AudioMicMute']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/next", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/next-static", value: "['XF86AudioNext', '<Ctrl>XF86AudioNext']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/on-screen-keyboard", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/pause", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/pause-static", value: "['XF86AudioPause']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/play", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/play-static", value: "['XF86AudioPlay', '<Ctrl>XF86AudioPlay']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/playback-forward", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/playback-forward-static", value: "['XF86AudioForward']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/playback-random", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/playback-random-static", value: "['XF86AudioRandomPlay']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/playback-repeat", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/playback-repeat-static", value: "['XF86AudioRepeat']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/playback-rewind", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/playback-rewind-static", value: "['XF86AudioRewind']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/power", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/power-static", value: "['XF86PowerOff']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/previous", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/previous-static", value: "['XF86AudioPrev', '<Ctrl>XF86AudioPrev']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/rfkill", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/rfkill-bluetooth", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/rfkill-bluetooth-static", value: "['XF86Bluetooth']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/rfkill-static", value: "['XF86WLAN', 'XF86UWB', 'XF86RFKill']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static", value: "['<Super>o', 'XF86RotationLockToggle']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/screen-brightness-cycle", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/screen-brightness-cycle-static", value: "['XF86MonBrightnessCycle']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/screen-brightness-down", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/screen-brightness-down-static", value: "['XF86MonBrightnessDown']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/screen-brightness-up", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/screen-brightness-up-static", value: "['XF86MonBrightnessUp']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver", value: "['<Super>l']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver-static", value: "['XF86ScreenSaver']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/search", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/search-static", value: "['XF86Search']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/stop", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/stop-static", value: "['XF86AudioStop']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/suspend", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/suspend-static", value: "['XF86Sleep']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/terminal", value: "['<Primary><Alt>t']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/toggle-contrast", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/touchpad-off", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/touchpad-off-static", value: "['XF86TouchpadOff']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/touchpad-on", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/touchpad-on-static", value: "['XF86TouchpadOn']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/touchpad-toggle", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/touchpad-toggle-static", value: "['XF86TouchpadToggle', '<Ctrl><Super>XF86TouchpadToggle']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-down", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-down-precise", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-down-precise-static", value: "['<Shift>XF86AudioLowerVolume', '<Ctrl><Shift>XF86AudioLowerVolume']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-down-quiet", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-down-quiet-static", value: "['<Alt>XF86AudioLowerVolume', '<Alt><Ctrl>XF86AudioLowerVolume']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-down-static", value: "['XF86AudioLowerVolume', '<Ctrl>XF86AudioLowerVolume']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-mute", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-mute-quiet", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-mute-quiet-static", value: "['<Alt>XF86AudioMute']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-mute-static", value: "['XF86AudioMute']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-up", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-up-precise", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-up-precise-static", value: "['<Shift>XF86AudioRaiseVolume', '<Ctrl><Shift>XF86AudioRaiseVolume']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-up-quiet", value: "['']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-up-quiet-static", value: "['<Alt>XF86AudioRaiseVolume', '<Alt><Ctrl>XF86AudioRaiseVolume']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/volume-up-static", value: "['XF86AudioRaiseVolume', '<Ctrl>XF86AudioRaiseVolume']" }
  - { key: "/org/gnome/settings-daemon/plugins/media-keys/www-static", value: "['XF86WWW']" }
  - { key: "/org/gnome/shell/keybindings/open-application-menu", value: "['<Super>F10']" }
  - { key: "/org/gnome/shell/keybindings/shift-overview-down", value: "['<Super><Alt>Down']" }
  - { key: "/org/gnome/shell/keybindings/shift-overview-up", value: "['<Super><Alt>Up']" }
  - { key: "/org/gnome/shell/keybindings/show-screenshot-ui", value: "['Print']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-1", value: "['<Super>1']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-2", value: "['<Super>2']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-3", value: "['<Super>3']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-4", value: "['<Super>4']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-5", value: "['<Super>5']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-6", value: "['<Super>6']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-7", value: "['<Super>7']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-8", value: "['<Super>8']" }
  - { key: "/org/gnome/shell/keybindings/switch-to-application-9", value: "['<Super>9']" }
  - { key: "/org/gnome/mutter/keybindings/rotate-monitor", value: "['XF86RotateWindows']" }
