---
- name: Install common APT packages
  ansible.builtin.apt:
    name:
      - anacron
      - clamav-daemon
      - clamav
      - code
      - cron
      - slack-desktop
      - simplescreenrecorder
    state: present
    update_cache: yes
