---
# ansible/roles/gnome-settings/tasks/main.yml
# Managed policy: only enforce opinionated settings we explicitly care about.
# All other GNOME settings are left to system defaults to reduce noise and churn.

- name: Apply curated GNOME dconf settings (minimal, opinionated)
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    # Shell and favorites
    - {
        key: "/org/gnome/shell/enabled-extensions",
        value: "['ding@rastersoft.com', 'pop-cosmic@system76.com', 'pop-shell@system76.com', 'system76-power@system76.com', 'ubuntu-appindicators@ubuntu.com', 'cosmic-dock@system76.com', 'cosmic-workspaces@system76.com', 'popx11gestures@system76.com', 'dash-to-panel@jderose9.github.com', 'sound-output-device-chooser@kgshank.net', 'lockkeys@vaina.lt', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'color-picker@tuberry']",
      }
    - {
        key: "/org/gnome/shell/favorite-apps",
        value: "['pop-cosmic-applications.desktop', 'com.google.Chrome.desktop', 'com.discordapp.Discord.desktop', 'slack.desktop', 'code.desktop', 'org.gnome.Terminal.desktop']",
      }

    # Dash to Panel (layout and key visuals)
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/animate-appicon-hover",
        value: "true",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/animate-appicon-hover-animation-extent",
        value: "{'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/appicon-margin",
        value: "8",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/appicon-padding",
        value: "4",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/dot-position",
        value: "'BOTTOM'",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/dot-style-focused",
        value: "'METRO'",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/dot-style-unfocused",
        value: "'METRO'",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/group-apps",
        value: "true",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/hotkeys-overlay-combo",
        value: "'TEMPORARILY'",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/leftbox-padding",
        value: "-1",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/multi-monitors",
        value: "true",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/panel-anchors",
        value: '''{"0":"MIDDLE","1":"MIDDLE"}''',
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/panel-element-positions",
        value: '''{"0":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}],"1":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}]}''',
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/panel-element-positions-monitors-sync",
        value: "true",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/panel-lengths",
        value: '''{"0":100,"1":100}''',
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/panel-sizes",
        value: '''{"0":48,"1":48}''',
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/status-icon-padding",
        value: "-1",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/show-appmenu",
        value: "true",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/show-apps-icon-file",
        value: "''",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/show-tooltip",
        value: "true",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/available-monitors",
        value: "[0, 1]",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/primary-monitor",
        value: "0",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/stockgs-keep-dash",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/stockgs-keep-top-panel",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/stockgs-panelbtn-click-only",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/trans-bg-color",
        value: "'#000000'",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/trans-gradient-bottom-opacity",
        value: "0.20000000000000001",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/trans-gradient-top-opacity",
        value: "0.0",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/trans-panel-opacity",
        value: "0.80000000000000004",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/trans-use-custom-bg",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/trans-use-custom-gradient",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/trans-use-custom-opacity",
        value: "false",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/tray-padding",
        value: "-1",
      }
    - {
        key: "/org/gnome/shell/extensions/dash-to-panel/window-preview-title-position",
        value: "'TOP'",
      }

    # Custom keybindings only (and the parent list)
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings",
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/']",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding",
        value: "'<Super>s'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command",
        value: "'flatpak run com.valvesoftware.Steam'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name",
        value: "'Open Steam'",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding",
        value: "'<Super>d'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command",
        value: "'flatpak run com.discordapp.Discord'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name",
        value: "'Open Discord'",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding",
        value: "'<Super>n'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command",
        value: "'gnome-text-editor'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name",
        value: "'Open Notes'",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/binding",
        value: "'<Super>w'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/command",
        value: "'sh /home/hcnureth/Development/start_work_env.sh &'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/name",
        value: "'Open Work'",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/binding",
        value: "'<Super>b'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/command",
        value: '''flatpak run com.google.Chrome --profile-directory="Default"''',
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/name",
        value: "'Open Chrome'",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/binding",
        value: "'<Super>g'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/command",
        value: '''flatpak run com.google.Chrome https://gemini.google.com/ --profile-directory="Default"''',
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/name",
        value: "'Open Gemini'",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/binding",
        value: "'<Super>y'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/command",
        value: '''flatpak run com.google.Chrome https://youtube.com/ --profile-directory="Default"''',
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/name",
        value: "'Open YouTube'",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/binding",
        value: "'<Super>p'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/command",
        value: '''flatpak run com.google.Chrome https://messages.google.com/ --profile-directory="Default"''',
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/name",
        value: "'Open Phone'",
      }

    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/binding",
        value: "'<Super>bracketright'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/command",
        value: "'simplescreenrecorder'",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/name",
        value: "'Record Screen'",
      }

    # Selected system keybindings
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/calculator",
        value: "['<Super>bracketleft']",
      }
    - {
        key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver",
        value: "['<Super>l']",
      }
  become: no
