---
- name: Ensure Flathub remote exists (user)
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: user
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak applications (user-level)
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.github.tchx84.Flatseal
      - com.google.Chrome
      - com.mattjakeman.ExtensionManager
      - com.valvesoftware.Steam
      - org.prismlauncher.PrismLauncher
      - org.vinegarhq.Sober
      - us.zoom.Zoom
    method: user
    state: present
    remote: flathub
